name: acme-booking

services:

# TODO Containerize App
#  app:
#    build:
#      ./

  db:
    container_name: acme_booking_db
    image: postgres:latest
    env_file:
      - docker.env
    environment:
      - TZ=Europe/Athens
      - PGTZ=Europe/Athens
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - acme-booking-network
    restart: always

  db-migration:
    container_name: liquibase_migration
    image: liquibase:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app/src/main/resources/liquibase:/liquibase/migrations
    command:
      - update-testing-rollback
    env_file:
      - docker.env
    environment:
      LIQUIBASE_DRIVER: "org.postgresql.Driver"
      LIQUIBASE_LOG_LEVEL: "info"
      LIQUIBASE_LIQUIBASE_SCHEMA_NAME: "public"
      LIQUIBASE_COMMAND_CHANGELOG_FILE: "/liquibase/migrations/master.xml"
    networks:
      - acme-booking-network

networks:
  acme-booking-network:
    driver: bridge